# Generated by Django 5.0.3 on 2024-03-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='name',
        ),
    ]
